/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/chat/': RouteRecordInfo<'/chat/', '/chat', Record<never, never>, Record<never, never>>,
    '/chat/detail/[id]': RouteRecordInfo<'/chat/detail/[id]', '/chat/detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/chat/history': RouteRecordInfo<'/chat/history', '/chat/history', Record<never, never>, Record<never, never>>,
    '/forum/': RouteRecordInfo<'/forum/', '/forum', Record<never, never>, Record<never, never>>,
    '/forum/detail/[id]': RouteRecordInfo<'/forum/detail/[id]', '/forum/detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/forum/publish': RouteRecordInfo<'/forum/publish', '/forum/publish', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    '/profile/': RouteRecordInfo<'/profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/profile/settings': RouteRecordInfo<'/profile/settings', '/profile/settings', Record<never, never>, Record<never, never>>,
    'reload': RouteRecordInfo<'reload', '/reload', Record<never, never>, Record<never, never>>,
    '/tools/': RouteRecordInfo<'/tools/', '/tools', Record<never, never>, Record<never, never>>,
    '/tools/breathing': RouteRecordInfo<'/tools/breathing', '/tools/breathing', Record<never, never>, Record<never, never>>,
    '/tools/meditation': RouteRecordInfo<'/tools/meditation', '/tools/meditation', Record<never, never>, Record<never, never>>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
  }
}
